### ISSUE TITLE
Weird output on certain aliases

### ISSUE THREAD

**Issue by Lense** [Homebrew/homebrew-aliases#3]
Running `brew alias -anything="12d"` gives traceback of 

    /usr/local/Library/brew.rb:101:in `exit'
    /usr/local/Library/brew.rb:101:in `<main>'

The alias still works, and the exit code is 0. From testing, it looks like it needs the alias to start with `-`, and the third character in the command needs to be a `d`. I have no clue why this happens...

(I found this by running `brew alias -Syu="update && brew info"`)

**Comment by UniqMartin** [comment]
The problem you're seeing here is that every argument to `brew` (it's not related specifically to `brew alias`) that starts with a dash (`-`) is interpreted as a list of short options. That means every character following the dash could possibly trigger something, if it is evaluated by the command. In this particular case you're seeing the expected behavior for when `-d` (short for `--debug`) is specified, which prints some output for the Homebrew run even if there was no failure.

The takeaway here is: Don't use aliases starting with a dash as that interferes with Homebrew's argument handling and `brew alias` cannot do anything to suppress this default behavior.
